language: python

dist: 'trusty'

python:
  - "2.7"
  - "3.6"

matrix:
  include:
    - python: "2.7"
    - python: "3.6"

before_install:
  - sudo apt-get -qq update

install:
  - pip install -r requirements-dev.txt
  - pip install .

script:
  - nosetests

notifications:
  email: false

deploy:
  provider: pypi
  user: "dev"
  password:
    secure: hhWdxzLRdBsSs0AxnDeQmqK9TLcod3eFBO0clumEoe92/y3Z86yhqjh9Y5zsElcbaqx9g5LYclnQTr/8uZZETGcnIx1cTVpMOerf6mN3Zq6GmX1vkxlbeF+vnw9aGZzeKKNBX3VzbgWxftAn/epOB41POXpQc4TrD01tYmaD+dI=
  on:
    tags: true
